config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save

    @flat.save ? (redirect_to flat_path(@flat)) : (render :new)
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="cards">
  <% @flats.each do |flat| %>
    <div class="card">
      <div class="imgcontainer">
        <img src=<%= flat.picture_url %>>
      </div>
      <h4><%= link_to flat.name, flat_path(flat) %></h4>
      <p><%= flat.address %></p>
      <p><%= flat.price_per_night %></p>
      <p><%= flat.number_of_guests %></p>
    </div>
  <% end %>
</div>


<%= link_to 'Add flat', new_flat_path %> |

app/views/flats/new.html.erb
<%= simple_form_for [ @flat ] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Add new flat", class: "btn btn-primary" %>
<% end %>

app/views/flats/show.html.erb
<h2><%= @flat.name %></h2>
<p><%= @flat.address %></p>
<p><%= @flat.description %></p>
<p><%= @flat.price_per_night %></p>
<p><%= @flat.number_of_guests %></p>

<%= link_to 'Back', flats_path %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>